apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    volumeMounts:
      - name: docker
        mountPath: /var/run/docker.sock
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
  nodeSelector:
    instance-type: spot